Testing fail on 0 tests

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -12,44 +12,7 @@ on:
     branches: master
 
 jobs:
-  sharedmerge:
-    outputs:
-      changed: ${{ steps.merge.outputs.changed }}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          token: ${{ secrets.ACTIONS_TOKEN }}
-
-      - name: Setup git
-        run: |
-          sudo apt install git
-          git config --global user.email "rickard.abraham@gmail.com"
-          git config --global user.name Mandera
-
-      - name: Shared merge and possible repush
-        id: merge
-        run: |
-          cd ..
-          git clone https://Mandera:${{ secrets.GIT_PASSWORD }}@github.com/ManderaGeneral/shared.git
-          cp -r shared/generalasterisk/. ${{ github.event.repository.name }}
-          cd ${{ github.event.repository.name }}
-
-          if [[ $(git status) != *"clean"* ]]; then
-            echo Package was not up to date so it will be updated
-            git add .
-            git commit -m "[CI AUTO] Updating shared files for this package." -m "${{ github.event.head_commit.message }}"
-            git push
-
-            echo '::set-output name=changed::true'
-          else
-            echo Package is up to date
-            echo '::set-output name=changed::false'
-          fi
-
   unittest:
-    needs: sharedmerge
-    if: needs.sharedmerge.outputs.changed == 'false' && !contains(github.event.head_commit.message, '[CI SKIP]')
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -72,7 +35,11 @@ jobs:
 
       - name: Run unittests
         run: |
-          python -m unittest discover ${{ github.event.repository.name }}/test
+          result=$(python -m unittest discover ${{ github.event.repository.name }} 2>&1)
+          if [[ $result == *"Ran 0 tests"* ]]; then
+          echo "FAILING: Couldn't find any tests"
+          exit 1
+          fi
 
 
   publisher:
@@ -153,6 +120,7 @@ jobs:
           pypi_versions=$(pip install ${{ github.event.repository.name }}== 2>&1) || :
           if [[ $pypi_versions == *"${{ env.NEW_VERSION }}"* ]]; then
           found_version=1
+          echo "Found new verson on PyPI!"
           break
           fi
           echo "Couldn't find new version on PyPI, trying again in 5 seconds"
